-- MySQL Script generated by MySQL Workbench
-- Tue Oct  1 19:01:21 2019
-- Model: MealPlanner2    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mealplanner2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mealplanner2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mealplanner2` DEFAULT CHARACTER SET utf8 ;
USE `mealplanner2` ;

-- -----------------------------------------------------
-- Table `mealplanner2`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mealplanner2`.`Users` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `security_level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mealplanner2`.`Recipes` (
  `recipe_id` INT NOT NULL,
  `recipe_name` VARCHAR(45) NOT NULL,
  `recipe_desc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`recipe_id`),
  UNIQUE INDEX `recipe_id_UNIQUE` (`recipe_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UsersRecipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mealplanner2`.`UsersRecipes` (
  `Users_user_id` INT NOT NULL,
  `Recipes_recipe_id` INT NOT NULL,
  PRIMARY KEY (`Users_user_id`, `Recipes_recipe_id`),
  INDEX `fk_Users_has_Recipes_Recipes1_idx` (`Recipes_recipe_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Recipes_Users_idx` (`Users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Recipes_Users`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `mealplanner2`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Recipes_Recipes1`
    FOREIGN KEY (`Recipes_recipe_id`)
    REFERENCES `mealplanner2`.`Recipes` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MealPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mealplanner2`.`MealPlan` (
  `MealPlan_id` INT NOT NULL,
  `meal_date` VARCHAR(45) NOT NULL,
  `meal_time` VARCHAR(45) NOT NULL,
  `Users_user_id` INT NOT NULL,
  PRIMARY KEY (`MealPlan_id`, `Users_user_id`),
  UNIQUE INDEX `MealPlan_id_UNIQUE` (`MealPlan_id` ASC) VISIBLE,
  INDEX `fk_MealPlan_Users1_idx` (`Users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_MealPlan_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `mealplanner2`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mealplanner2`.`Ingredients` (
  `ingredient_id` INT NOT NULL,
  `ingredient_name` VARCHAR(45) NOT NULL,
  `ingredient_desc` VARCHAR(45) NOT NULL,
  `serving_metric` VARCHAR(45) NOT NULL,
  `calories` INT NULL,
  `g_unsaturated_fat` INT NULL,
  `g_saturated_fat` INT NULL,
  `g_trans_fat` INT NULL,
  `mg_cholesterol` INT NULL,
  `mg_sodium` INT NULL,
  `g_fiber` INT NULL,
  `g_sugar` INT NULL,
  `g_protein` INT NULL,
  UNIQUE INDEX `ingredient_id_UNIQUE` (`ingredient_id` ASC) VISIBLE,
  PRIMARY KEY (`ingredient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mealplanner2`.`RecipesIngredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mealplanner2`.`RecipesIngredients` (
  `Recipes_recipe_id` INT NOT NULL,
  `Ingredients_ingredient_id` INT NOT NULL,
  `num_ingredient_servings` INT NULL,
  PRIMARY KEY (`Recipes_recipe_id`, `Ingredients_ingredient_id`),
  INDEX `fk_Recipes_has_Ingredients_Ingredients1_idx` (`Ingredients_ingredient_id` ASC) VISIBLE,
  INDEX `fk_Recipes_has_Ingredients_Recipes1_idx` (`Recipes_recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_Recipes_has_Ingredients_Recipes1`
    FOREIGN KEY (`Recipes_recipe_id`)
    REFERENCES `mealplanner2`.`Recipes` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipes_has_Ingredients_Ingredients1`
    FOREIGN KEY (`Ingredients_ingredient_id`)
    REFERENCES `mealplanner2`.`Ingredients` (`ingredient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
